version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: catalog-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
      - ./init_data_base.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
    command: mongod --auth --bind_ip_all
    networks:
      - app-network

  catalog-app:
    build: .
    container_name: catalog-app
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env  # Загружаем переменные из .env
    ports:
      - "8000:8000"
      - "50051:50051"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge