version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: catalog-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
      - ./init_data_base.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
    command: mongod --auth --bind_ip_all
    networks:
      - app-network

  catalog-app:
    build: .
    container_name: catalog-app
    restart: always
    depends_on:
      - mongodb
    environment:
      # MongoDB connection
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_DATABASE: catalog_db
      
      # App settings
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      GRPC_PORT: 50051
      API_V1_PREFIX: /api/v1
      DEBUG: "true"
      
    ports:
      - "8000:8000"    # FastAPI HTTP
      - "50051:50051"  # gRPC
    volumes:
      - ./src:/app/src              # –î–ª—è —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏
      - ./proto:/app/proto          # Protobuf —Ñ–∞–π–ª—ã
    networks:
      - app-network
    command: >
      sh -c "
        echo '‚è≥ –û–∂–∏–¥–∞–µ–º –∑–∞–ø—É—Å–∫ MongoDB...' &&
        sleep 10 &&
        echo 'üöÄ –ó–∞–ø—É—Å–∫–∞–µ–º –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ...' &&
        python main.py
      "

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge